In [1]:
pip install bs4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bs4 in C:\Users\gvrna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in C:\Users\gvrna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from bs4) (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\gvrna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\gvrna\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from beautifulsoup4->bs4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\gvrna\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = "https://companiesmarketcap.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

In [4]:
print(soup.title.string)

Companies ranked by Market Cap - CompaniesMarketCap.com

In [5]:
print(soup.title)

<title>Companies ranked by Market Cap - CompaniesMarketCap.com</title>

In [6]:
soup.find('table')

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [7]:
soup.find_all('table')

[<table class="default-table table marketcap-table dataTable" style="width:100%">
 <thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [8]:
soup.find('table',class_ = "default-table table marketcap-table dataTable")

<table class="default-table table marketcap-table dataTable" style="width:100%">
<thead><tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr></thead> <tbody>

In [9]:
soup.find_all('th')

[<th class="th-id-1" tid="1"></th>,
 <th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th>,
 <th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th>,
 <th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th>,
 <th class="th-id-5 th-price sorting text-right" tid="5">Price</th>,
 <th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th>,
 <th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th>,
 <th class="th-id-8 th-country sorting" tid="8">Country</th>]

In [10]:
word_titles = soup.find_all('th')
word_titles

[<th class="th-id-1" tid="1"></th>,
 <th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th>,
 <th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th>,
 <th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th>,
 <th class="th-id-5 th-price sorting text-right" tid="5">Price</th>,
 <th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th>,
 <th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th>,
 <th class="th-id-8 th-country sorting" tid="8">Country</th>]

In [11]:
word_titles = [title.text.strip() for title in word_titles]
word_titles

['',
 'Rank',
 'Name',
 'Market Cap',
 'Price',
 'Today',
 'Price (30 days)',
 'Country']

In [12]:
import pandas as pd

In [14]:
df = pd.DataFrame(columns = word_titles)
df

Empty DataFrame
Columns: [, Rank, Name, Market Cap, Price, Today, Price (30 days), Country]
Index: []

In [15]:
column_data = soup.find_all('tr')
column_data

[<tr><th class="th-id-1" tid="1"></th><th class="th-id-2 th-rank sorting sorting_asc" tid="2">Rank</th><th class="th-id-3 th-name sorting" tid="3">Name<div class="afterElem"></div></th><th class="th-id-4 th-mcap sorting text-right" tid="4">Market Cap</th><th class="th-id-5 th-price sorting text-right" tid="5">Price</th><th class="th-id-6 th-1d sorting rh-sm" tid="6">Today</th><th class="th-id-7 th-30d no-sort" tid="7">Price (30 days)</th><th class="th-id-8 th-country sorting" tid="8">Country</th></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="29" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="1">1</td><td class="name-td"><div class="logo-container"><img alt="NVIDIA logo" class="company-logo" loading="lazy" src="/img/company-logos/64/NVDA.png"/></div><div class="name-div"><a href="/nvidia/marketcap/"><div class="company-name">NVIDIA</div><div class="company-code"><span class="rank d-none"></span>NVDA</div></a></div></td><td class="td-right" data-sort="5443804987392"><span class="currency-symbol-left">$</span>5.443 T</td><td class="td-right" data-sort="22476">$224.76</td><td class="rh-sm" data-sort="188"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.88%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,38 L10,37 L15,34 L20,34 L25,29 L30,27 L35,28 L40,25 L45,25 L50,27 L55,25 L60,27 L65,21 L70,16 L75,18 L80,20 L85,27 L90,28 L95,28 L100,29 L105,21 L110,19 L115,17 L120,14 L125,13 L130,10 L135,3 L140,10 L145,12 L150,13 L155,10"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="4" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="2">2</td><td class="name-td"><div class="logo-container"><img alt="Alphabet (Google) logo" class="company-logo" loading="lazy" src="/img/company-logos/64/GOOG.png"/></div><div class="name-div"><a href="/alphabet-google/marketcap/"><div class="company-name">Alphabet (Google)</div><div class="company-code"><span class="rank d-none"></span>GOOG</div></a></div></td><td class="td-right" data-sort="4632945360896"><span class="currency-symbol-left">$</span>4.632 T</td><td class="td-right" data-sort="38240">$382.40</td><td class="rh-sm" data-sort="-65"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.65%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,36 L15,36 L20,35 L25,30 L30,29 L35,29 L40,27 L45,28 L50,30 L55,27 L60,27 L65,26 L70,23 L75,24 L80,24 L85,10 L90,9 L95,11 L100,9 L105,5 L110,4 L115,4 L120,8 L125,9 L130,3 L135,4 L140,5 L145,5 L150,9 L155,10"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="2" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="3">3</td><td class="name-td"><div class="logo-container"><img alt="Apple logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AAPL.D.png" data-img-path="/img/company-logos/64/AAPL.png" loading="lazy" src="/img/company-logos/64/AAPL.png"/></div><div class="name-div"><a href="/apple/marketcap/"><div class="company-name">Apple</div><div class="company-code"><span class="rank d-none"></span>AAPL</div></a></div></td><td class="td-right" data-sort="4407969185792"><span class="currency-symbol-left">$</span>4.407 T</td><td class="td-right" data-sort="30012">$300.12</td><td class="rh-sm" data-sort="38"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.38%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,35 L15,35 L20,36 L25,37 L30,30 L35,33 L40,27 L45,25 L50,31 L55,25 L60,25 L65,27 L70,30 L75,27 L80,27 L85,26 L90,19 L95,22 L100,16 L105,13 L110,13 L115,9 L120,9 L125,7 L130,4 L135,5 L140,3 L145,5 L150,4 L155,3"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="1" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="4">4</td><td class="name-td"><div class="logo-container"><img alt="Microsoft logo" class="company-logo" loading="lazy" src="/img/company-logos/64/MSFT.png"/></div><div class="name-div"><a href="/microsoft/marketcap/"><div class="company-name">Microsoft</div><div class="company-code"><span class="rank d-none"></span>MSFT</div></a></div></td><td class="td-right" data-sort="3077117575168"><span class="currency-symbol-left">$</span>3.077 T</td><td class="td-right" data-sort="41423.5">$414.24</td><td class="rh-sm" data-sort="-76"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.76%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,39 L10,40 L15,41 L20,33 L25,27 L30,16 L35,11 L40,9 L45,12 L50,8 L55,3 L60,14 L65,8 L70,8 L75,5 L80,8 L85,18 L90,14 L95,15 L100,16 L105,15 L110,10 L115,14 L120,15 L125,18 L130,20 L135,17 L140,10 L145,9 L150,12 L155,14"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="3" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="5">5</td><td class="name-td"><div class="logo-container"><img alt="Amazon logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AMZN.D.png" data-img-path="/img/company-logos/64/AMZN.png" loading="lazy" src="/img/company-logos/64/AMZN.png"/></div><div class="name-div"><a href="/amazon/marketcap/"><div class="company-name">Amazon</div><div class="company-code"><span class="rank d-none"></span>AMZN</div></a></div></td><td class="td-right" data-sort="2825354739712"><span class="currency-symbol-left">$</span>2.825 T</td><td class="td-right" data-sort="26265">$262.65</td><td class="rh-sm" data-sort="128"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.28%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,29 L15,26 L20,25 L25,19 L30,19 L35,19 L40,18 L45,20 L50,19 L55,15 L60,15 L65,10 L70,12 L75,12 L80,10 L85,9 L90,7 L95,5 L100,4 L105,3 L110,5 L115,4 L120,7 L125,9 L130,6 L135,8 L140,10 L145,9 L150,13 L155,11"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="17" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="6">6</td><td class="name-td"><div class="logo-container"><img alt="TSMC logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSM.png"/></div><div class="name-div"><a href="/tsmc/marketcap/"><div class="company-name">TSMC</div><div class="company-code"><span class="rank d-none"></span>TSM</div></a></div></td><td class="td-right" data-sort="2080683589632"><span class="currency-symbol-left">$</span>2.080 T</td><td class="td-right" data-sort="40117.5">$401.18</td><td class="rh-sm" data-sort="218"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.18%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,30 L10,31 L15,28 L20,29 L25,23 L30,26 L35,32 L40,28 L45,30 L50,29 L55,19 L60,22 L65,12 L70,10 L75,17 L80,16 L85,15 L90,14 L95,12 L100,16 L105,3 L110,6 L115,7 L120,11 L125,14 L130,13 L135,4 L140,11 L145,15 L150,17 L155,12"></path></svg></td><td>🇹🇼 <span class="responsive-hidden">Taiwan</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="58" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="7">7</td><td class="name-td"><div class="logo-container"><img alt="Broadcom logo" class="company-logo" loading="lazy" src="/img/company-logos/64/AVGO.png"/></div><div class="name-div"><a href="/broadcom/marketcap/"><div class="company-name">Broadcom</div><div class="company-code"><span class="rank d-none"></span>AVGO</div></a></div></td><td class="td-right" data-sort="1986785181696"><span class="currency-symbol-left">$</span>1.986 T</td><td class="td-right" data-sort="41962.5">$419.62</td><td class="rh-sm" data-sort="208"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.08%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,35 L10,33 L15,28 L20,25 L25,24 L30,18 L35,18 L40,15 L45,17 L50,17 L55,9 L60,10 L65,9 L70,11 L75,17 L80,15 L85,11 L90,10 L95,11 L100,7 L105,8 L110,13 L115,7 L120,7 L125,10 L130,11 L135,3 L140,8 L145,10 L150,13 L155,10"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="558" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="8">8</td><td class="name-td"><div class="logo-container"><img alt="Saudi Aramco logo" class="company-logo" loading="lazy" src="/img/company-logos/64/2222.SR.png"/></div><div class="name-div"><a href="/saudi-aramco/marketcap/"><div class="company-name">Saudi Aramco</div><div class="company-code"><span class="rank d-none"></span>2222.SR</div></a></div></td><td class="td-right" data-sort="1796061308284"><span class="currency-symbol-left">$</span>1.796 T</td><td class="td-right" data-sort="742.458">$7.42</td><td class="rh-sm" data-sort="-36"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.36%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,41 L10,32 L15,34 L20,17 L25,26 L30,19 L35,20 L40,32 L45,32 L50,34 L55,30 L60,32 L65,36 L70,30 L75,22 L80,18 L85,11 L90,21 L95,15 L100,10 L105,40 L110,32 L115,24 L120,15 L125,8 L130,5 L135,13 L140,10 L145,10 L150,3 L155,7"></path></svg></td><td>🇸🇦 <span class="responsive-hidden">S. Arabia</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="15" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="9" moves="1">9</td><td class="name-td"><div class="logo-container"><img alt="Tesla logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSLA.png"/></div><div class="name-div"><a href="/tesla/marketcap/"><div class="company-name">Tesla</div><div class="company-code"><span class="rank d-none"></span>TSLA</div></a></div></td><td class="td-right" data-sort="1540184735744"><span class="currency-symbol-left">$</span>1.540 T</td><td class="td-right" data-sort="41009">$410.09</td><td class="rh-sm" data-sort="148"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.48%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,41 L10,40 L15,39 L20,38 L25,33 L30,23 L35,24 L40,20 L45,23 L50,25 L55,25 L60,30 L65,29 L70,28 L75,29 L80,30 L85,27 L90,23 L95,23 L100,24 L105,20 L110,15 L115,9 L120,3 L125,7 L130,3 L135,4 L140,12 L145,16 L150,18 L155,16"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="72379" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="10" moves="-1">10</td><td class="name-td"><div class="logo-container"><img alt="Meta Platforms (Facebook) logo" class="company-logo" data-img-dark-path="/img/company-logos/64/META.D.png" data-img-path="/img/company-logos/64/META.png" loading="lazy" src="/img/company-logos/64/META.png"/></div><div class="name-div"><a href="/meta-platforms/marketcap/"><div class="company-name">Meta Platforms (Facebook)</div><div class="company-code"><span class="rank d-none"></span>META</div></a></div></td><td class="td-right" data-sort="1529749045248"><span class="currency-symbol-left">$</span>1.529 T</td><td class="td-right" data-sort="60263.8">$602.64</td><td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,28 L10,23 L15,23 L20,21 L25,12 L30,9 L35,7 L40,3 L45,9 L50,10 L55,8 L60,13 L65,8 L70,6 L75,9 L80,10 L85,29 L90,30 L95,29 L100,31 L105,28 L110,27 L115,29 L120,33 L125,32 L130,27 L135,26 L140,28 L145,29 L150,32 L155,32"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="417" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="11">11</td><td class="name-td"><div class="logo-container"><img alt="Samsung logo" class="company-logo" data-img-dark-path="/img/company-logos/64/005930.KS.D.png" data-img-path="/img/company-logos/64/005930.KS.png" loading="lazy" src="/img/company-logos/64/005930.KS.png"/></div><div class="name-div"><a href="/samsung/marketcap/"><div class="company-name">Samsung</div><div class="company-code"><span class="rank d-none"></span>005930.KS</div></a></div></td><td class="td-right" data-sort="1203409941255"><span class="currency-symbol-left">$</span>1.203 T</td><td class="td-right" data-sort="18326.3">$183.26</td><td class="rh-sm" data-sort="18"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.18%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,38 L15,37 L20,39 L25,37 L30,35 L35,33 L40,34 L45,34 L50,32 L55,33 L60,30 L65,32 L70,30 L75,31 L80,30 L85,32 L90,32 L95,27 L100,27 L105,14 L110,12 L115,14 L120,7 L125,9 L130,8 L135,3 L140,13 L145,9 L150,11 L155,11"></path></svg></td><td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="9" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="12">12</td><td class="name-td"><div class="logo-container"><img alt="Walmart logo" class="company-logo" data-img-dark-path="/img/company-logos/64/WMT.D.png" data-img-path="/img/company-logos/64/WMT.png" loading="lazy" src="/img/company-logos/64/WMT.png"/></div><div class="name-div"><a href="/walmart/marketcap/"><div class="company-name">Walmart</div><div class="company-code"><span class="rank d-none"></span>WMT</div></a></div></td><td class="td-right" data-sort="1055279415296"><span class="currency-symbol-left">$</span>1.055 T</td><td class="td-right" data-sort="13239">$132.39</td><td class="rh-sm" data-sort="-135"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.35%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,26 L10,19 L15,27 L20,34 L25,33 L30,34 L35,33 L40,25 L45,23 L50,18 L55,17 L60,10 L65,17 L70,24 L75,24 L80,23 L85,10 L90,11 L95,16 L100,14 L105,16 L110,16 L115,15 L120,24 L125,15 L130,12 L135,9 L140,12 L145,6 L150,3 L155,9"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="10" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="13">13</td><td class="name-td"><div class="logo-container"><img alt="Berkshire Hathaway  logo" class="company-logo" data-img-dark-path="/img/company-logos/64/BRK-B.D.png" data-img-path="/img/company-logos/64/BRK-B.png" loading="lazy" src="/img/company-logos/64/BRK-B.png"/></div><div class="name-div"><a href="/berkshire-hathaway/marketcap/"><div class="company-name">Berkshire Hathaway </div><div class="company-code"><span class="rank d-none"></span>BRK-B</div></a></div></td><td class="td-right" data-sort="1032076132352"><span class="currency-symbol-left">$</span>1.032 T</td><td class="td-right" data-sort="47851">$478.51</td><td class="rh-sm" data-sort="-41"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.41%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,17 L10,8 L15,17 L20,17 L25,21 L30,27 L35,25 L40,26 L45,30 L50,36 L55,41 L60,32 L65,35 L70,29 L75,20 L80,24 L85,27 L90,28 L95,36 L100,41 L105,34 L110,25 L115,24 L120,18 L125,9 L130,8 L135,10 L140,12 L145,3 L150,16 L155,19"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="46" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="14">14</td><td class="name-td"><div class="logo-container"><img alt="Eli Lilly logo" class="company-logo" loading="lazy" src="/img/company-logos/64/LLY.png"/></div><div class="name-div"><a href="/eli-lilly/marketcap/"><div class="company-name">Eli Lilly</div><div class="company-code"><span class="rank d-none"></span>LLY</div></a></div></td><td class="td-right" data-sort="915194249216"><span class="currency-symbol-left">$</span>915.19 B</td><td class="td-right" data-sort="102630">$1,026</td><td class="rh-sm" data-sort="48"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.48%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,24 L5,19 L10,19 L15,22 L20,24 L25,26 L30,29 L35,30 L40,25 L45,26 L50,30 L55,26 L60,27 L65,34 L70,37 L75,36 L80,41 L85,23 L90,17 L95,16 L100,11 L105,12 L110,14 L115,20 L120,16 L125,11 L130,6 L135,7 L140,8 L145,11 L150,4 L155,3"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="69141" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="15">15</td><td class="name-td"><div class="logo-container"><img alt="SK Hynix logo" class="company-logo" loading="lazy" src="/img/company-logos/64/000660.KS.png"/></div><div class="name-div"><a href="/sk-hynix/marketcap/"><div class="company-name">SK Hynix</div><div class="company-code"><span class="rank d-none"></span>000660.KS</div></a></div></td><td class="td-right" data-sort="822491493536"><span class="currency-symbol-left">$</span>822.49 B</td><td class="td-right" data-sort="115868">$1,159</td><td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,38 L15,37 L20,37 L25,34 L30,33 L35,32 L40,33 L45,32 L50,30 L55,30 L60,30 L65,30 L70,28 L75,27 L80,27 L85,28 L90,28 L95,22 L100,22 L105,16 L110,15 L115,13 L120,6 L125,8 L130,3 L135,3 L140,9 L145,8 L150,11 L155,11"></path></svg></td><td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td></tr>,
 <tr><td class="fav"><img alt="favorite icon" data-id="433" data-type="company" src="/img/fav.svg?v2"/></td><td class="rank-td td-right" data-sort="16">16</td><td class="name-td"><div class="logo-container"><img alt="JPMorgan Chase logo" class="company-logo" data-img-dark-path="/img/company-logos/64/JPM.D.png" data-img-path="/img/company-logos/64/JPM.png" loading="lazy" src="/img/company-logos/64/JPM.png"/></div><div class="name-div"><a href="/jp-morgan-chase/marketcap/"><div class="company-name">JPMorgan Chase</div><div class="company-code"><span class="rank d-none"></span>JPM</div></a></div></td><td class="td-right" data-sort="803076308992"><span class="currency-symbol-left">$</span>803.07 B</td><td class="td-right" data-sort="29971">$299.71</td><td class="rh-sm" data-sort="136"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.36%</span></td><td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,19 L10,15 L15,16 L20,9 L25,13 L30,23 L35,16 L40,15 L45,3 L50,10 L55,10 L60,12 L65,19 L70,13 L75,13 L80,17 L85,10 L90,11 L95,20 L100,17 L105,7 L110,22 L115,30 L120,33 L125,25 L130,33 L135,33 L140,37 L145,32 L150,41 L155,34"></path></svg></td><td>🇺🇸 <span class="responsive-hidden">USA</span></td></tr>,

In [16]:
for row in column_data:
    print(row.find_all('td'))

[]
[<td class="fav"><img alt="favorite icon" data-id="29" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="1">1</td>, <td class="name-td"><div class="logo-container"><img alt="NVIDIA logo" class="company-logo" loading="lazy" src="/img/company-logos/64/NVDA.png"/></div><div class="name-div"><a href="/nvidia/marketcap/"><div class="company-name">NVIDIA</div><div class="company-code"><span class="rank d-none"></span>NVDA</div></a></div></td>, <td class="td-right" data-sort="5443804987392"><span class="currency-symbol-left">$</span>5.443 T</td>, <td class="td-right" data-sort="22476">$224.76</td>, <td class="rh-sm" data-sort="188"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.88%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,38 L10,37 L15,34 L20,34 L25,29 L30,27 L35,28 L40,25 L45,25 L50,27 L55,25 L60,27 L65,21 L70,16 L75,18 L80,20 L85,27 L90,28 L95,28 L100,29 L105,21 L110,19 L115,17 L120,14 L125,13 L130,10 L135,3 L140,10 L145,12 L150,13 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="4" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="2">2</td>, <td class="name-td"><div class="logo-container"><img alt="Alphabet (Google) logo" class="company-logo" loading="lazy" src="/img/company-logos/64/GOOG.png"/></div><div class="name-div"><a href="/alphabet-google/marketcap/"><div class="company-name">Alphabet (Google)</div><div class="company-code"><span class="rank d-none"></span>GOOG</div></a></div></td>, <td class="td-right" data-sort="4632945360896"><span class="currency-symbol-left">$</span>4.632 T</td>, <td class="td-right" data-sort="38240">$382.40</td>, <td class="rh-sm" data-sort="-65"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.65%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,36 L15,36 L20,35 L25,30 L30,29 L35,29 L40,27 L45,28 L50,30 L55,27 L60,27 L65,26 L70,23 L75,24 L80,24 L85,10 L90,9 L95,11 L100,9 L105,5 L110,4 L115,4 L120,8 L125,9 L130,3 L135,4 L140,5 L145,5 L150,9 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="2" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="3">3</td>, <td class="name-td"><div class="logo-container"><img alt="Apple logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AAPL.D.png" data-img-path="/img/company-logos/64/AAPL.png" loading="lazy" src="/img/company-logos/64/AAPL.png"/></div><div class="name-div"><a href="/apple/marketcap/"><div class="company-name">Apple</div><div class="company-code"><span class="rank d-none"></span>AAPL</div></a></div></td>, <td class="td-right" data-sort="4407969185792"><span class="currency-symbol-left">$</span>4.407 T</td>, <td class="td-right" data-sort="30012">$300.12</td>, <td class="rh-sm" data-sort="38"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.38%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,35 L15,35 L20,36 L25,37 L30,30 L35,33 L40,27 L45,25 L50,31 L55,25 L60,25 L65,27 L70,30 L75,27 L80,27 L85,26 L90,19 L95,22 L100,16 L105,13 L110,13 L115,9 L120,9 L125,7 L130,4 L135,5 L140,3 L145,5 L150,4 L155,3"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="1" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="4">4</td>, <td class="name-td"><div class="logo-container"><img alt="Microsoft logo" class="company-logo" loading="lazy" src="/img/company-logos/64/MSFT.png"/></div><div class="name-div"><a href="/microsoft/marketcap/"><div class="company-name">Microsoft</div><div class="company-code"><span class="rank d-none"></span>MSFT</div></a></div></td>, <td class="td-right" data-sort="3077117575168"><span class="currency-symbol-left">$</span>3.077 T</td>, <td class="td-right" data-sort="41423.5">$414.24</td>, <td class="rh-sm" data-sort="-76"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.76%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,39 L10,40 L15,41 L20,33 L25,27 L30,16 L35,11 L40,9 L45,12 L50,8 L55,3 L60,14 L65,8 L70,8 L75,5 L80,8 L85,18 L90,14 L95,15 L100,16 L105,15 L110,10 L115,14 L120,15 L125,18 L130,20 L135,17 L140,10 L145,9 L150,12 L155,14"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="3" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="5">5</td>, <td class="name-td"><div class="logo-container"><img alt="Amazon logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AMZN.D.png" data-img-path="/img/company-logos/64/AMZN.png" loading="lazy" src="/img/company-logos/64/AMZN.png"/></div><div class="name-div"><a href="/amazon/marketcap/"><div class="company-name">Amazon</div><div class="company-code"><span class="rank d-none"></span>AMZN</div></a></div></td>, <td class="td-right" data-sort="2825354739712"><span class="currency-symbol-left">$</span>2.825 T</td>, <td class="td-right" data-sort="26265">$262.65</td>, <td class="rh-sm" data-sort="128"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.28%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,29 L15,26 L20,25 L25,19 L30,19 L35,19 L40,18 L45,20 L50,19 L55,15 L60,15 L65,10 L70,12 L75,12 L80,10 L85,9 L90,7 L95,5 L100,4 L105,3 L110,5 L115,4 L120,7 L125,9 L130,6 L135,8 L140,10 L145,9 L150,13 L155,11"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="17" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="6">6</td>, <td class="name-td"><div class="logo-container"><img alt="TSMC logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSM.png"/></div><div class="name-div"><a href="/tsmc/marketcap/"><div class="company-name">TSMC</div><div class="company-code"><span class="rank d-none"></span>TSM</div></a></div></td>, <td class="td-right" data-sort="2080683589632"><span class="currency-symbol-left">$</span>2.080 T</td>, <td class="td-right" data-sort="40117.5">$401.18</td>, <td class="rh-sm" data-sort="218"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.18%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,30 L10,31 L15,28 L20,29 L25,23 L30,26 L35,32 L40,28 L45,30 L50,29 L55,19 L60,22 L65,12 L70,10 L75,17 L80,16 L85,15 L90,14 L95,12 L100,16 L105,3 L110,6 L115,7 L120,11 L125,14 L130,13 L135,4 L140,11 L145,15 L150,17 L155,12"></path></svg></td>, <td>🇹🇼 <span class="responsive-hidden">Taiwan</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="58" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="7">7</td>, <td class="name-td"><div class="logo-container"><img alt="Broadcom logo" class="company-logo" loading="lazy" src="/img/company-logos/64/AVGO.png"/></div><div class="name-div"><a href="/broadcom/marketcap/"><div class="company-name">Broadcom</div><div class="company-code"><span class="rank d-none"></span>AVGO</div></a></div></td>, <td class="td-right" data-sort="1986785181696"><span class="currency-symbol-left">$</span>1.986 T</td>, <td class="td-right" data-sort="41962.5">$419.62</td>, <td class="rh-sm" data-sort="208"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.08%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,35 L10,33 L15,28 L20,25 L25,24 L30,18 L35,18 L40,15 L45,17 L50,17 L55,9 L60,10 L65,9 L70,11 L75,17 L80,15 L85,11 L90,10 L95,11 L100,7 L105,8 L110,13 L115,7 L120,7 L125,10 L130,11 L135,3 L140,8 L145,10 L150,13 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="558" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="8">8</td>, <td class="name-td"><div class="logo-container"><img alt="Saudi Aramco logo" class="company-logo" loading="lazy" src="/img/company-logos/64/2222.SR.png"/></div><div class="name-div"><a href="/saudi-aramco/marketcap/"><div class="company-name">Saudi Aramco</div><div class="company-code"><span class="rank d-none"></span>2222.SR</div></a></div></td>, <td class="td-right" data-sort="1796061308284"><span class="currency-symbol-left">$</span>1.796 T</td>, <td class="td-right" data-sort="742.458">$7.42</td>, <td class="rh-sm" data-sort="-36"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.36%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,41 L10,32 L15,34 L20,17 L25,26 L30,19 L35,20 L40,32 L45,32 L50,34 L55,30 L60,32 L65,36 L70,30 L75,22 L80,18 L85,11 L90,21 L95,15 L100,10 L105,40 L110,32 L115,24 L120,15 L125,8 L130,5 L135,13 L140,10 L145,10 L150,3 L155,7"></path></svg></td>, <td>🇸🇦 <span class="responsive-hidden">S. Arabia</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="15" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="9" moves="1">9</td>, <td class="name-td"><div class="logo-container"><img alt="Tesla logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSLA.png"/></div><div class="name-div"><a href="/tesla/marketcap/"><div class="company-name">Tesla</div><div class="company-code"><span class="rank d-none"></span>TSLA</div></a></div></td>, <td class="td-right" data-sort="1540184735744"><span class="currency-symbol-left">$</span>1.540 T</td>, <td class="td-right" data-sort="41009">$410.09</td>, <td class="rh-sm" data-sort="148"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.48%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,41 L10,40 L15,39 L20,38 L25,33 L30,23 L35,24 L40,20 L45,23 L50,25 L55,25 L60,30 L65,29 L70,28 L75,29 L80,30 L85,27 L90,23 L95,23 L100,24 L105,20 L110,15 L115,9 L120,3 L125,7 L130,3 L135,4 L140,12 L145,16 L150,18 L155,16"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="72379" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="10" moves="-1">10</td>, <td class="name-td"><div class="logo-container"><img alt="Meta Platforms (Facebook) logo" class="company-logo" data-img-dark-path="/img/company-logos/64/META.D.png" data-img-path="/img/company-logos/64/META.png" loading="lazy" src="/img/company-logos/64/META.png"/></div><div class="name-div"><a href="/meta-platforms/marketcap/"><div class="company-name">Meta Platforms (Facebook)</div><div class="company-code"><span class="rank d-none"></span>META</div></a></div></td>, <td class="td-right" data-sort="1529749045248"><span class="currency-symbol-left">$</span>1.529 T</td>, <td class="td-right" data-sort="60263.8">$602.64</td>, <td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,28 L10,23 L15,23 L20,21 L25,12 L30,9 L35,7 L40,3 L45,9 L50,10 L55,8 L60,13 L65,8 L70,6 L75,9 L80,10 L85,29 L90,30 L95,29 L100,31 L105,28 L110,27 L115,29 L120,33 L125,32 L130,27 L135,26 L140,28 L145,29 L150,32 L155,32"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="417" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="11">11</td>, <td class="name-td"><div class="logo-container"><img alt="Samsung logo" class="company-logo" data-img-dark-path="/img/company-logos/64/005930.KS.D.png" data-img-path="/img/company-logos/64/005930.KS.png" loading="lazy" src="/img/company-logos/64/005930.KS.png"/></div><div class="name-div"><a href="/samsung/marketcap/"><div class="company-name">Samsung</div><div class="company-code"><span class="rank d-none"></span>005930.KS</div></a></div></td>, <td class="td-right" data-sort="1203409941255"><span class="currency-symbol-left">$</span>1.203 T</td>, <td class="td-right" data-sort="18326.3">$183.26</td>, <td class="rh-sm" data-sort="18"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.18%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,38 L15,37 L20,39 L25,37 L30,35 L35,33 L40,34 L45,34 L50,32 L55,33 L60,30 L65,32 L70,30 L75,31 L80,30 L85,32 L90,32 L95,27 L100,27 L105,14 L110,12 L115,14 L120,7 L125,9 L130,8 L135,3 L140,13 L145,9 L150,11 L155,11"></path></svg></td>, <td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="9" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="12">12</td>, <td class="name-td"><div class="logo-container"><img alt="Walmart logo" class="company-logo" data-img-dark-path="/img/company-logos/64/WMT.D.png" data-img-path="/img/company-logos/64/WMT.png" loading="lazy" src="/img/company-logos/64/WMT.png"/></div><div class="name-div"><a href="/walmart/marketcap/"><div class="company-name">Walmart</div><div class="company-code"><span class="rank d-none"></span>WMT</div></a></div></td>, <td class="td-right" data-sort="1055279415296"><span class="currency-symbol-left">$</span>1.055 T</td>, <td class="td-right" data-sort="13239">$132.39</td>, <td class="rh-sm" data-sort="-135"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.35%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,26 L10,19 L15,27 L20,34 L25,33 L30,34 L35,33 L40,25 L45,23 L50,18 L55,17 L60,10 L65,17 L70,24 L75,24 L80,23 L85,10 L90,11 L95,16 L100,14 L105,16 L110,16 L115,15 L120,24 L125,15 L130,12 L135,9 L140,12 L145,6 L150,3 L155,9"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="10" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="13">13</td>, <td class="name-td"><div class="logo-container"><img alt="Berkshire Hathaway  logo" class="company-logo" data-img-dark-path="/img/company-logos/64/BRK-B.D.png" data-img-path="/img/company-logos/64/BRK-B.png" loading="lazy" src="/img/company-logos/64/BRK-B.png"/></div><div class="name-div"><a href="/berkshire-hathaway/marketcap/"><div class="company-name">Berkshire Hathaway </div><div class="company-code"><span class="rank d-none"></span>BRK-B</div></a></div></td>, <td class="td-right" data-sort="1032076132352"><span class="currency-symbol-left">$</span>1.032 T</td>, <td class="td-right" data-sort="47851">$478.51</td>, <td class="rh-sm" data-sort="-41"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.41%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,17 L10,8 L15,17 L20,17 L25,21 L30,27 L35,25 L40,26 L45,30 L50,36 L55,41 L60,32 L65,35 L70,29 L75,20 L80,24 L85,27 L90,28 L95,36 L100,41 L105,34 L110,25 L115,24 L120,18 L125,9 L130,8 L135,10 L140,12 L145,3 L150,16 L155,19"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="46" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="14">14</td>, <td class="name-td"><div class="logo-container"><img alt="Eli Lilly logo" class="company-logo" loading="lazy" src="/img/company-logos/64/LLY.png"/></div><div class="name-div"><a href="/eli-lilly/marketcap/"><div class="company-name">Eli Lilly</div><div class="company-code"><span class="rank d-none"></span>LLY</div></a></div></td>, <td class="td-right" data-sort="915194249216"><span class="currency-symbol-left">$</span>915.19 B</td>, <td class="td-right" data-sort="102630">$1,026</td>, <td class="rh-sm" data-sort="48"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.48%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,24 L5,19 L10,19 L15,22 L20,24 L25,26 L30,29 L35,30 L40,25 L45,26 L50,30 L55,26 L60,27 L65,34 L70,37 L75,36 L80,41 L85,23 L90,17 L95,16 L100,11 L105,12 L110,14 L115,20 L120,16 L125,11 L130,6 L135,7 L140,8 L145,11 L150,4 L155,3"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="69141" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="15">15</td>, <td class="name-td"><div class="logo-container"><img alt="SK Hynix logo" class="company-logo" loading="lazy" src="/img/company-logos/64/000660.KS.png"/></div><div class="name-div"><a href="/sk-hynix/marketcap/"><div class="company-name">SK Hynix</div><div class="company-code"><span class="rank d-none"></span>000660.KS</div></a></div></td>, <td class="td-right" data-sort="822491493536"><span class="currency-symbol-left">$</span>822.49 B</td>, <td class="td-right" data-sort="115868">$1,159</td>, <td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,38 L15,37 L20,37 L25,34 L30,33 L35,32 L40,33 L45,32 L50,30 L55,30 L60,30 L65,30 L70,28 L75,27 L80,27 L85,28 L90,28 L95,22 L100,22 L105,16 L110,15 L115,13 L120,6 L125,8 L130,3 L135,3 L140,9 L145,8 L150,11 L155,11"></path></svg></td>, <td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="433" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="16">16</td>, <td class="name-td"><div class="logo-container"><img alt="JPMorgan Chase logo" class="company-logo" data-img-dark-path="/img/company-logos/64/JPM.D.png" data-img-path="/img/company-logos/64/JPM.png" loading="lazy" src="/img/company-logos/64/JPM.png"/></div><div class="name-div"><a href="/jp-morgan-chase/marketcap/"><div class="company-name">JPMorgan Chase</div><div class="company-code"><span class="rank d-none"></span>JPM</div></a></div></td>, <td class="td-right" data-sort="803076308992"><span class="currency-symbol-left">$</span>803.07 B</td>, <td class="td-right" data-sort="29971">$299.71</td>, <td class="rh-sm" data-sort="136"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.36%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,19 L10,15 L15,16 L20,9 L25,13 L30,23 L35,16 L40,15 L45,3 L50,10 L55,10 L60,12 L65,19 L70,13 L75,13 L80,17 L85,10 L90,11 L95,20 L100,17 L105,7 L110,22 L115,30 L120,33 L125,25 L130,33 L135,33 L140,37 L145,32 L150,41 L155,34"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]

In [17]:
for row in column_data:
    row_data = row.find_all('td')
    print(row_data)

[]
[<td class="fav"><img alt="favorite icon" data-id="29" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="1">1</td>, <td class="name-td"><div class="logo-container"><img alt="NVIDIA logo" class="company-logo" loading="lazy" src="/img/company-logos/64/NVDA.png"/></div><div class="name-div"><a href="/nvidia/marketcap/"><div class="company-name">NVIDIA</div><div class="company-code"><span class="rank d-none"></span>NVDA</div></a></div></td>, <td class="td-right" data-sort="5443804987392"><span class="currency-symbol-left">$</span>5.443 T</td>, <td class="td-right" data-sort="22476">$224.76</td>, <td class="rh-sm" data-sort="188"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.88%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,38 L10,37 L15,34 L20,34 L25,29 L30,27 L35,28 L40,25 L45,25 L50,27 L55,25 L60,27 L65,21 L70,16 L75,18 L80,20 L85,27 L90,28 L95,28 L100,29 L105,21 L110,19 L115,17 L120,14 L125,13 L130,10 L135,3 L140,10 L145,12 L150,13 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="4" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="2">2</td>, <td class="name-td"><div class="logo-container"><img alt="Alphabet (Google) logo" class="company-logo" loading="lazy" src="/img/company-logos/64/GOOG.png"/></div><div class="name-div"><a href="/alphabet-google/marketcap/"><div class="company-name">Alphabet (Google)</div><div class="company-code"><span class="rank d-none"></span>GOOG</div></a></div></td>, <td class="td-right" data-sort="4632945360896"><span class="currency-symbol-left">$</span>4.632 T</td>, <td class="td-right" data-sort="38240">$382.40</td>, <td class="rh-sm" data-sort="-65"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.65%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,36 L15,36 L20,35 L25,30 L30,29 L35,29 L40,27 L45,28 L50,30 L55,27 L60,27 L65,26 L70,23 L75,24 L80,24 L85,10 L90,9 L95,11 L100,9 L105,5 L110,4 L115,4 L120,8 L125,9 L130,3 L135,4 L140,5 L145,5 L150,9 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="2" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="3">3</td>, <td class="name-td"><div class="logo-container"><img alt="Apple logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AAPL.D.png" data-img-path="/img/company-logos/64/AAPL.png" loading="lazy" src="/img/company-logos/64/AAPL.png"/></div><div class="name-div"><a href="/apple/marketcap/"><div class="company-name">Apple</div><div class="company-code"><span class="rank d-none"></span>AAPL</div></a></div></td>, <td class="td-right" data-sort="4407969185792"><span class="currency-symbol-left">$</span>4.407 T</td>, <td class="td-right" data-sort="30012">$300.12</td>, <td class="rh-sm" data-sort="38"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.38%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,35 L15,35 L20,36 L25,37 L30,30 L35,33 L40,27 L45,25 L50,31 L55,25 L60,25 L65,27 L70,30 L75,27 L80,27 L85,26 L90,19 L95,22 L100,16 L105,13 L110,13 L115,9 L120,9 L125,7 L130,4 L135,5 L140,3 L145,5 L150,4 L155,3"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="1" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="4">4</td>, <td class="name-td"><div class="logo-container"><img alt="Microsoft logo" class="company-logo" loading="lazy" src="/img/company-logos/64/MSFT.png"/></div><div class="name-div"><a href="/microsoft/marketcap/"><div class="company-name">Microsoft</div><div class="company-code"><span class="rank d-none"></span>MSFT</div></a></div></td>, <td class="td-right" data-sort="3077117575168"><span class="currency-symbol-left">$</span>3.077 T</td>, <td class="td-right" data-sort="41423.5">$414.24</td>, <td class="rh-sm" data-sort="-76"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.76%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,39 L10,40 L15,41 L20,33 L25,27 L30,16 L35,11 L40,9 L45,12 L50,8 L55,3 L60,14 L65,8 L70,8 L75,5 L80,8 L85,18 L90,14 L95,15 L100,16 L105,15 L110,10 L115,14 L120,15 L125,18 L130,20 L135,17 L140,10 L145,9 L150,12 L155,14"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="3" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="5">5</td>, <td class="name-td"><div class="logo-container"><img alt="Amazon logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AMZN.D.png" data-img-path="/img/company-logos/64/AMZN.png" loading="lazy" src="/img/company-logos/64/AMZN.png"/></div><div class="name-div"><a href="/amazon/marketcap/"><div class="company-name">Amazon</div><div class="company-code"><span class="rank d-none"></span>AMZN</div></a></div></td>, <td class="td-right" data-sort="2825354739712"><span class="currency-symbol-left">$</span>2.825 T</td>, <td class="td-right" data-sort="26265">$262.65</td>, <td class="rh-sm" data-sort="128"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.28%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,29 L15,26 L20,25 L25,19 L30,19 L35,19 L40,18 L45,20 L50,19 L55,15 L60,15 L65,10 L70,12 L75,12 L80,10 L85,9 L90,7 L95,5 L100,4 L105,3 L110,5 L115,4 L120,7 L125,9 L130,6 L135,8 L140,10 L145,9 L150,13 L155,11"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="17" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="6">6</td>, <td class="name-td"><div class="logo-container"><img alt="TSMC logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSM.png"/></div><div class="name-div"><a href="/tsmc/marketcap/"><div class="company-name">TSMC</div><div class="company-code"><span class="rank d-none"></span>TSM</div></a></div></td>, <td class="td-right" data-sort="2080683589632"><span class="currency-symbol-left">$</span>2.080 T</td>, <td class="td-right" data-sort="40117.5">$401.18</td>, <td class="rh-sm" data-sort="218"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.18%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,30 L10,31 L15,28 L20,29 L25,23 L30,26 L35,32 L40,28 L45,30 L50,29 L55,19 L60,22 L65,12 L70,10 L75,17 L80,16 L85,15 L90,14 L95,12 L100,16 L105,3 L110,6 L115,7 L120,11 L125,14 L130,13 L135,4 L140,11 L145,15 L150,17 L155,12"></path></svg></td>, <td>🇹🇼 <span class="responsive-hidden">Taiwan</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="58" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="7">7</td>, <td class="name-td"><div class="logo-container"><img alt="Broadcom logo" class="company-logo" loading="lazy" src="/img/company-logos/64/AVGO.png"/></div><div class="name-div"><a href="/broadcom/marketcap/"><div class="company-name">Broadcom</div><div class="company-code"><span class="rank d-none"></span>AVGO</div></a></div></td>, <td class="td-right" data-sort="1986785181696"><span class="currency-symbol-left">$</span>1.986 T</td>, <td class="td-right" data-sort="41962.5">$419.62</td>, <td class="rh-sm" data-sort="208"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.08%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,35 L10,33 L15,28 L20,25 L25,24 L30,18 L35,18 L40,15 L45,17 L50,17 L55,9 L60,10 L65,9 L70,11 L75,17 L80,15 L85,11 L90,10 L95,11 L100,7 L105,8 L110,13 L115,7 L120,7 L125,10 L130,11 L135,3 L140,8 L145,10 L150,13 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="558" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="8">8</td>, <td class="name-td"><div class="logo-container"><img alt="Saudi Aramco logo" class="company-logo" loading="lazy" src="/img/company-logos/64/2222.SR.png"/></div><div class="name-div"><a href="/saudi-aramco/marketcap/"><div class="company-name">Saudi Aramco</div><div class="company-code"><span class="rank d-none"></span>2222.SR</div></a></div></td>, <td class="td-right" data-sort="1796061308284"><span class="currency-symbol-left">$</span>1.796 T</td>, <td class="td-right" data-sort="742.458">$7.42</td>, <td class="rh-sm" data-sort="-36"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.36%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,41 L10,32 L15,34 L20,17 L25,26 L30,19 L35,20 L40,32 L45,32 L50,34 L55,30 L60,32 L65,36 L70,30 L75,22 L80,18 L85,11 L90,21 L95,15 L100,10 L105,40 L110,32 L115,24 L120,15 L125,8 L130,5 L135,13 L140,10 L145,10 L150,3 L155,7"></path></svg></td>, <td>🇸🇦 <span class="responsive-hidden">S. Arabia</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="15" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="9" moves="1">9</td>, <td class="name-td"><div class="logo-container"><img alt="Tesla logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSLA.png"/></div><div class="name-div"><a href="/tesla/marketcap/"><div class="company-name">Tesla</div><div class="company-code"><span class="rank d-none"></span>TSLA</div></a></div></td>, <td class="td-right" data-sort="1540184735744"><span class="currency-symbol-left">$</span>1.540 T</td>, <td class="td-right" data-sort="41009">$410.09</td>, <td class="rh-sm" data-sort="148"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.48%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,41 L10,40 L15,39 L20,38 L25,33 L30,23 L35,24 L40,20 L45,23 L50,25 L55,25 L60,30 L65,29 L70,28 L75,29 L80,30 L85,27 L90,23 L95,23 L100,24 L105,20 L110,15 L115,9 L120,3 L125,7 L130,3 L135,4 L140,12 L145,16 L150,18 L155,16"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="72379" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="10" moves="-1">10</td>, <td class="name-td"><div class="logo-container"><img alt="Meta Platforms (Facebook) logo" class="company-logo" data-img-dark-path="/img/company-logos/64/META.D.png" data-img-path="/img/company-logos/64/META.png" loading="lazy" src="/img/company-logos/64/META.png"/></div><div class="name-div"><a href="/meta-platforms/marketcap/"><div class="company-name">Meta Platforms (Facebook)</div><div class="company-code"><span class="rank d-none"></span>META</div></a></div></td>, <td class="td-right" data-sort="1529749045248"><span class="currency-symbol-left">$</span>1.529 T</td>, <td class="td-right" data-sort="60263.8">$602.64</td>, <td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,28 L10,23 L15,23 L20,21 L25,12 L30,9 L35,7 L40,3 L45,9 L50,10 L55,8 L60,13 L65,8 L70,6 L75,9 L80,10 L85,29 L90,30 L95,29 L100,31 L105,28 L110,27 L115,29 L120,33 L125,32 L130,27 L135,26 L140,28 L145,29 L150,32 L155,32"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="417" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="11">11</td>, <td class="name-td"><div class="logo-container"><img alt="Samsung logo" class="company-logo" data-img-dark-path="/img/company-logos/64/005930.KS.D.png" data-img-path="/img/company-logos/64/005930.KS.png" loading="lazy" src="/img/company-logos/64/005930.KS.png"/></div><div class="name-div"><a href="/samsung/marketcap/"><div class="company-name">Samsung</div><div class="company-code"><span class="rank d-none"></span>005930.KS</div></a></div></td>, <td class="td-right" data-sort="1203409941255"><span class="currency-symbol-left">$</span>1.203 T</td>, <td class="td-right" data-sort="18326.3">$183.26</td>, <td class="rh-sm" data-sort="18"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.18%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,38 L15,37 L20,39 L25,37 L30,35 L35,33 L40,34 L45,34 L50,32 L55,33 L60,30 L65,32 L70,30 L75,31 L80,30 L85,32 L90,32 L95,27 L100,27 L105,14 L110,12 L115,14 L120,7 L125,9 L130,8 L135,3 L140,13 L145,9 L150,11 L155,11"></path></svg></td>, <td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="9" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="12">12</td>, <td class="name-td"><div class="logo-container"><img alt="Walmart logo" class="company-logo" data-img-dark-path="/img/company-logos/64/WMT.D.png" data-img-path="/img/company-logos/64/WMT.png" loading="lazy" src="/img/company-logos/64/WMT.png"/></div><div class="name-div"><a href="/walmart/marketcap/"><div class="company-name">Walmart</div><div class="company-code"><span class="rank d-none"></span>WMT</div></a></div></td>, <td class="td-right" data-sort="1055279415296"><span class="currency-symbol-left">$</span>1.055 T</td>, <td class="td-right" data-sort="13239">$132.39</td>, <td class="rh-sm" data-sort="-135"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.35%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,26 L10,19 L15,27 L20,34 L25,33 L30,34 L35,33 L40,25 L45,23 L50,18 L55,17 L60,10 L65,17 L70,24 L75,24 L80,23 L85,10 L90,11 L95,16 L100,14 L105,16 L110,16 L115,15 L120,24 L125,15 L130,12 L135,9 L140,12 L145,6 L150,3 L155,9"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="10" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="13">13</td>, <td class="name-td"><div class="logo-container"><img alt="Berkshire Hathaway  logo" class="company-logo" data-img-dark-path="/img/company-logos/64/BRK-B.D.png" data-img-path="/img/company-logos/64/BRK-B.png" loading="lazy" src="/img/company-logos/64/BRK-B.png"/></div><div class="name-div"><a href="/berkshire-hathaway/marketcap/"><div class="company-name">Berkshire Hathaway </div><div class="company-code"><span class="rank d-none"></span>BRK-B</div></a></div></td>, <td class="td-right" data-sort="1032076132352"><span class="currency-symbol-left">$</span>1.032 T</td>, <td class="td-right" data-sort="47851">$478.51</td>, <td class="rh-sm" data-sort="-41"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.41%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,17 L10,8 L15,17 L20,17 L25,21 L30,27 L35,25 L40,26 L45,30 L50,36 L55,41 L60,32 L65,35 L70,29 L75,20 L80,24 L85,27 L90,28 L95,36 L100,41 L105,34 L110,25 L115,24 L120,18 L125,9 L130,8 L135,10 L140,12 L145,3 L150,16 L155,19"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="46" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="14">14</td>, <td class="name-td"><div class="logo-container"><img alt="Eli Lilly logo" class="company-logo" loading="lazy" src="/img/company-logos/64/LLY.png"/></div><div class="name-div"><a href="/eli-lilly/marketcap/"><div class="company-name">Eli Lilly</div><div class="company-code"><span class="rank d-none"></span>LLY</div></a></div></td>, <td class="td-right" data-sort="915194249216"><span class="currency-symbol-left">$</span>915.19 B</td>, <td class="td-right" data-sort="102630">$1,026</td>, <td class="rh-sm" data-sort="48"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.48%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,24 L5,19 L10,19 L15,22 L20,24 L25,26 L30,29 L35,30 L40,25 L45,26 L50,30 L55,26 L60,27 L65,34 L70,37 L75,36 L80,41 L85,23 L90,17 L95,16 L100,11 L105,12 L110,14 L115,20 L120,16 L125,11 L130,6 L135,7 L140,8 L145,11 L150,4 L155,3"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="69141" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="15">15</td>, <td class="name-td"><div class="logo-container"><img alt="SK Hynix logo" class="company-logo" loading="lazy" src="/img/company-logos/64/000660.KS.png"/></div><div class="name-div"><a href="/sk-hynix/marketcap/"><div class="company-name">SK Hynix</div><div class="company-code"><span class="rank d-none"></span>000660.KS</div></a></div></td>, <td class="td-right" data-sort="822491493536"><span class="currency-symbol-left">$</span>822.49 B</td>, <td class="td-right" data-sort="115868">$1,159</td>, <td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,38 L15,37 L20,37 L25,34 L30,33 L35,32 L40,33 L45,32 L50,30 L55,30 L60,30 L65,30 L70,28 L75,27 L80,27 L85,28 L90,28 L95,22 L100,22 L105,16 L110,15 L115,13 L120,6 L125,8 L130,3 L135,3 L140,9 L145,8 L150,11 L155,11"></path></svg></td>, <td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td>]
[<td class="fav"><img alt="favorite icon" data-id="433" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="16">16</td>, <td class="name-td"><div class="logo-container"><img alt="JPMorgan Chase logo" class="company-logo" data-img-dark-path="/img/company-logos/64/JPM.D.png" data-img-path="/img/company-logos/64/JPM.png" loading="lazy" src="/img/company-logos/64/JPM.png"/></div><div class="name-div"><a href="/jp-morgan-chase/marketcap/"><div class="company-name">JPMorgan Chase</div><div class="company-code"><span class="rank d-none"></span>JPM</div></a></div></td>, <td class="td-right" data-sort="803076308992"><span class="currency-symbol-left">$</span>803.07 B</td>, <td class="td-right" data-sort="29971">$299.71</td>, <td class="rh-sm" data-sort="136"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.36%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,38 L5,19 L10,15 L15,16 L20,9 L25,13 L30,23 L35,16 L40,15 L45,3 L50,10 L55,10 L60,12 L65,19 L70,13 L75,13 L80,17 L85,10 L90,11 L95,20 L100,17 L105,7 L110,22 L115,30 L120,33 L125,25 L130,33 L135,33 L140,37 L145,32 L150,41 L155,34"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]

In [18]:
for row in column_data:
    row_data = row.find_all('td')
    print(row_data)
    individual_data = [data.text.strip() for data in row_data]
    print(individual_data)

[]
[]
[<td class="fav"><img alt="favorite icon" data-id="29" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="1">1</td>, <td class="name-td"><div class="logo-container"><img alt="NVIDIA logo" class="company-logo" loading="lazy" src="/img/company-logos/64/NVDA.png"/></div><div class="name-div"><a href="/nvidia/marketcap/"><div class="company-name">NVIDIA</div><div class="company-code"><span class="rank d-none"></span>NVDA</div></a></div></td>, <td class="td-right" data-sort="5443804987392"><span class="currency-symbol-left">$</span>5.443 T</td>, <td class="td-right" data-sort="22476">$224.76</td>, <td class="rh-sm" data-sort="188"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.88%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,38 L10,37 L15,34 L20,34 L25,29 L30,27 L35,28 L40,25 L45,25 L50,27 L55,25 L60,27 L65,21 L70,16 L75,18 L80,20 L85,27 L90,28 L95,28 L100,29 L105,21 L110,19 L115,17 L120,14 L125,13 L130,10 L135,3 L140,10 L145,12 L150,13 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '1', 'NVIDIANVDA', '$5.443 T', '$224.76', '1.88%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="4" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="2">2</td>, <td class="name-td"><div class="logo-container"><img alt="Alphabet (Google) logo" class="company-logo" loading="lazy" src="/img/company-logos/64/GOOG.png"/></div><div class="name-div"><a href="/alphabet-google/marketcap/"><div class="company-name">Alphabet (Google)</div><div class="company-code"><span class="rank d-none"></span>GOOG</div></a></div></td>, <td class="td-right" data-sort="4632945360896"><span class="currency-symbol-left">$</span>4.632 T</td>, <td class="td-right" data-sort="38240">$382.40</td>, <td class="rh-sm" data-sort="-65"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.65%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,36 L15,36 L20,35 L25,30 L30,29 L35,29 L40,27 L45,28 L50,30 L55,27 L60,27 L65,26 L70,23 L75,24 L80,24 L85,10 L90,9 L95,11 L100,9 L105,5 L110,4 L115,4 L120,8 L125,9 L130,3 L135,4 L140,5 L145,5 L150,9 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '2', 'Alphabet (Google)GOOG', '$4.632 T', '$382.40', '0.65%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="2" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="3">3</td>, <td class="name-td"><div class="logo-container"><img alt="Apple logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AAPL.D.png" data-img-path="/img/company-logos/64/AAPL.png" loading="lazy" src="/img/company-logos/64/AAPL.png"/></div><div class="name-div"><a href="/apple/marketcap/"><div class="company-name">Apple</div><div class="company-code"><span class="rank d-none"></span>AAPL</div></a></div></td>, <td class="td-right" data-sort="4407969185792"><span class="currency-symbol-left">$</span>4.407 T</td>, <td class="td-right" data-sort="30012">$300.12</td>, <td class="rh-sm" data-sort="38"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.38%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,35 L15,35 L20,36 L25,37 L30,30 L35,33 L40,27 L45,25 L50,31 L55,25 L60,25 L65,27 L70,30 L75,27 L80,27 L85,26 L90,19 L95,22 L100,16 L105,13 L110,13 L115,9 L120,9 L125,7 L130,4 L135,5 L140,3 L145,5 L150,4 L155,3"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '3', 'AppleAAPL', '$4.407 T', '$300.12', '0.38%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="1" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="4">4</td>, <td class="name-td"><div class="logo-container"><img alt="Microsoft logo" class="company-logo" loading="lazy" src="/img/company-logos/64/MSFT.png"/></div><div class="name-div"><a href="/microsoft/marketcap/"><div class="company-name">Microsoft</div><div class="company-code"><span class="rank d-none"></span>MSFT</div></a></div></td>, <td class="td-right" data-sort="3077117575168"><span class="currency-symbol-left">$</span>3.077 T</td>, <td class="td-right" data-sort="41423.5">$414.24</td>, <td class="rh-sm" data-sort="-76"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.76%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,39 L10,40 L15,41 L20,33 L25,27 L30,16 L35,11 L40,9 L45,12 L50,8 L55,3 L60,14 L65,8 L70,8 L75,5 L80,8 L85,18 L90,14 L95,15 L100,16 L105,15 L110,10 L115,14 L120,15 L125,18 L130,20 L135,17 L140,10 L145,9 L150,12 L155,14"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '4', 'MicrosoftMSFT', '$3.077 T', '$414.24', '0.76%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="3" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="5">5</td>, <td class="name-td"><div class="logo-container"><img alt="Amazon logo" class="company-logo" data-img-dark-path="/img/company-logos/64/AMZN.D.png" data-img-path="/img/company-logos/64/AMZN.png" loading="lazy" src="/img/company-logos/64/AMZN.png"/></div><div class="name-div"><a href="/amazon/marketcap/"><div class="company-name">Amazon</div><div class="company-code"><span class="rank d-none"></span>AMZN</div></a></div></td>, <td class="td-right" data-sort="2825354739712"><span class="currency-symbol-left">$</span>2.825 T</td>, <td class="td-right" data-sort="26265">$262.65</td>, <td class="rh-sm" data-sort="128"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.28%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,29 L15,26 L20,25 L25,19 L30,19 L35,19 L40,18 L45,20 L50,19 L55,15 L60,15 L65,10 L70,12 L75,12 L80,10 L85,9 L90,7 L95,5 L100,4 L105,3 L110,5 L115,4 L120,7 L125,9 L130,6 L135,8 L140,10 L145,9 L150,13 L155,11"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '5', 'AmazonAMZN', '$2.825 T', '$262.65', '1.28%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="17" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="6">6</td>, <td class="name-td"><div class="logo-container"><img alt="TSMC logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSM.png"/></div><div class="name-div"><a href="/tsmc/marketcap/"><div class="company-name">TSMC</div><div class="company-code"><span class="rank d-none"></span>TSM</div></a></div></td>, <td class="td-right" data-sort="2080683589632"><span class="currency-symbol-left">$</span>2.080 T</td>, <td class="td-right" data-sort="40117.5">$401.18</td>, <td class="rh-sm" data-sort="218"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.18%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,30 L10,31 L15,28 L20,29 L25,23 L30,26 L35,32 L40,28 L45,30 L50,29 L55,19 L60,22 L65,12 L70,10 L75,17 L80,16 L85,15 L90,14 L95,12 L100,16 L105,3 L110,6 L115,7 L120,11 L125,14 L130,13 L135,4 L140,11 L145,15 L150,17 L155,12"></path></svg></td>, <td>🇹🇼 <span class="responsive-hidden">Taiwan</span></td>]
['', '6', 'TSMCTSM', '$2.080 T', '$401.18', '2.18%', '', '🇹🇼 Taiwan']
[<td class="fav"><img alt="favorite icon" data-id="58" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="7">7</td>, <td class="name-td"><div class="logo-container"><img alt="Broadcom logo" class="company-logo" loading="lazy" src="/img/company-logos/64/AVGO.png"/></div><div class="name-div"><a href="/broadcom/marketcap/"><div class="company-name">Broadcom</div><div class="company-code"><span class="rank d-none"></span>AVGO</div></a></div></td>, <td class="td-right" data-sort="1986785181696"><span class="currency-symbol-left">$</span>1.986 T</td>, <td class="td-right" data-sort="41962.5">$419.62</td>, <td class="rh-sm" data-sort="208"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>2.08%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,35 L10,33 L15,28 L20,25 L25,24 L30,18 L35,18 L40,15 L45,17 L50,17 L55,9 L60,10 L65,9 L70,11 L75,17 L80,15 L85,11 L90,10 L95,11 L100,7 L105,8 L110,13 L115,7 L120,7 L125,10 L130,11 L135,3 L140,8 L145,10 L150,13 L155,10"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '7', 'BroadcomAVGO', '$1.986 T', '$419.62', '2.08%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="558" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="8">8</td>, <td class="name-td"><div class="logo-container"><img alt="Saudi Aramco logo" class="company-logo" loading="lazy" src="/img/company-logos/64/2222.SR.png"/></div><div class="name-div"><a href="/saudi-aramco/marketcap/"><div class="company-name">Saudi Aramco</div><div class="company-code"><span class="rank d-none"></span>2222.SR</div></a></div></td>, <td class="td-right" data-sort="1796061308284"><span class="currency-symbol-left">$</span>1.796 T</td>, <td class="td-right" data-sort="742.458">$7.42</td>, <td class="rh-sm" data-sort="-36"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.36%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,41 L10,32 L15,34 L20,17 L25,26 L30,19 L35,20 L40,32 L45,32 L50,34 L55,30 L60,32 L65,36 L70,30 L75,22 L80,18 L85,11 L90,21 L95,15 L100,10 L105,40 L110,32 L115,24 L120,15 L125,8 L130,5 L135,13 L140,10 L145,10 L150,3 L155,7"></path></svg></td>, <td>🇸🇦 <span class="responsive-hidden">S. Arabia</span></td>]
['', '8', 'Saudi Aramco2222.SR', '$1.796 T', '$7.42', '0.36%', '', '🇸🇦 S. Arabia']
[<td class="fav"><img alt="favorite icon" data-id="15" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="9" moves="1">9</td>, <td class="name-td"><div class="logo-container"><img alt="Tesla logo" class="company-logo" loading="lazy" src="/img/company-logos/64/TSLA.png"/></div><div class="name-div"><a href="/tesla/marketcap/"><div class="company-name">Tesla</div><div class="company-code"><span class="rank d-none"></span>TSLA</div></a></div></td>, <td class="td-right" data-sort="1540184735744"><span class="currency-symbol-left">$</span>1.540 T</td>, <td class="td-right" data-sort="41009">$410.09</td>, <td class="rh-sm" data-sort="148"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>1.48%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,40 L5,41 L10,40 L15,39 L20,38 L25,33 L30,23 L35,24 L40,20 L45,23 L50,25 L55,25 L60,30 L65,29 L70,28 L75,29 L80,30 L85,27 L90,23 L95,23 L100,24 L105,20 L110,15 L115,9 L120,3 L125,7 L130,3 L135,4 L140,12 L145,16 L150,18 L155,16"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '9', 'TeslaTSLA', '$1.540 T', '$410.09', '1.48%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="72379" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="10" moves="-1">10</td>, <td class="name-td"><div class="logo-container"><img alt="Meta Platforms (Facebook) logo" class="company-logo" data-img-dark-path="/img/company-logos/64/META.D.png" data-img-path="/img/company-logos/64/META.png" loading="lazy" src="/img/company-logos/64/META.png"/></div><div class="name-div"><a href="/meta-platforms/marketcap/"><div class="company-name">Meta Platforms (Facebook)</div><div class="company-code"><span class="rank d-none"></span>META</div></a></div></td>, <td class="td-right" data-sort="1529749045248"><span class="currency-symbol-left">$</span>1.529 T</td>, <td class="td-right" data-sort="60263.8">$602.64</td>, <td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,28 L10,23 L15,23 L20,21 L25,12 L30,9 L35,7 L40,3 L45,9 L50,10 L55,8 L60,13 L65,8 L70,6 L75,9 L80,10 L85,29 L90,30 L95,29 L100,31 L105,28 L110,27 L115,29 L120,33 L125,32 L130,27 L135,26 L140,28 L145,29 L150,32 L155,32"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '10', 'Meta Platforms (Facebook)META', '$1.529 T', '$602.64', '0.00%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="417" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="11">11</td>, <td class="name-td"><div class="logo-container"><img alt="Samsung logo" class="company-logo" data-img-dark-path="/img/company-logos/64/005930.KS.D.png" data-img-path="/img/company-logos/64/005930.KS.png" loading="lazy" src="/img/company-logos/64/005930.KS.png"/></div><div class="name-div"><a href="/samsung/marketcap/"><div class="company-name">Samsung</div><div class="company-code"><span class="rank d-none"></span>005930.KS</div></a></div></td>, <td class="td-right" data-sort="1203409941255"><span class="currency-symbol-left">$</span>1.203 T</td>, <td class="td-right" data-sort="18326.3">$183.26</td>, <td class="rh-sm" data-sort="18"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.18%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,36 L10,38 L15,37 L20,39 L25,37 L30,35 L35,33 L40,34 L45,34 L50,32 L55,33 L60,30 L65,32 L70,30 L75,31 L80,30 L85,32 L90,32 L95,27 L100,27 L105,14 L110,12 L115,14 L120,7 L125,9 L130,8 L135,3 L140,13 L145,9 L150,11 L155,11"></path></svg></td>, <td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td>]
['', '11', 'Samsung005930.KS', '$1.203 T', '$183.26', '0.18%', '', '🇰🇷 S. Korea']
[<td class="fav"><img alt="favorite icon" data-id="9" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="12">12</td>, <td class="name-td"><div class="logo-container"><img alt="Walmart logo" class="company-logo" data-img-dark-path="/img/company-logos/64/WMT.D.png" data-img-path="/img/company-logos/64/WMT.png" loading="lazy" src="/img/company-logos/64/WMT.png"/></div><div class="name-div"><a href="/walmart/marketcap/"><div class="company-name">Walmart</div><div class="company-code"><span class="rank d-none"></span>WMT</div></a></div></td>, <td class="td-right" data-sort="1055279415296"><span class="currency-symbol-left">$</span>1.055 T</td>, <td class="td-right" data-sort="13239">$132.39</td>, <td class="rh-sm" data-sort="-135"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>1.35%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,26 L10,19 L15,27 L20,34 L25,33 L30,34 L35,33 L40,25 L45,23 L50,18 L55,17 L60,10 L65,17 L70,24 L75,24 L80,23 L85,10 L90,11 L95,16 L100,14 L105,16 L110,16 L115,15 L120,24 L125,15 L130,12 L135,9 L140,12 L145,6 L150,3 L155,9"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '12', 'WalmartWMT', '$1.055 T', '$132.39', '1.35%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="10" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="13">13</td>, <td class="name-td"><div class="logo-container"><img alt="Berkshire Hathaway  logo" class="company-logo" data-img-dark-path="/img/company-logos/64/BRK-B.D.png" data-img-path="/img/company-logos/64/BRK-B.png" loading="lazy" src="/img/company-logos/64/BRK-B.png"/></div><div class="name-div"><a href="/berkshire-hathaway/marketcap/"><div class="company-name">Berkshire Hathaway </div><div class="company-code"><span class="rank d-none"></span>BRK-B</div></a></div></td>, <td class="td-right" data-sort="1032076132352"><span class="currency-symbol-left">$</span>1.032 T</td>, <td class="td-right" data-sort="47851">$478.51</td>, <td class="rh-sm" data-sort="-41"><span class="percentage-red"><svg class="a" viewbox="0 0 12 12"><path d="m2 4h8l-4 4z"></path></svg>0.41%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,20 L5,17 L10,8 L15,17 L20,17 L25,21 L30,27 L35,25 L40,26 L45,30 L50,36 L55,41 L60,32 L65,35 L70,29 L75,20 L80,24 L85,27 L90,28 L95,36 L100,41 L105,34 L110,25 L115,24 L120,18 L125,9 L130,8 L135,10 L140,12 L145,3 L150,16 L155,19"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '13', 'Berkshire Hathaway BRK-B', '$1.032 T', '$478.51', '0.41%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="46" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="14">14</td>, <td class="name-td"><div class="logo-container"><img alt="Eli Lilly logo" class="company-logo" loading="lazy" src="/img/company-logos/64/LLY.png"/></div><div class="name-div"><a href="/eli-lilly/marketcap/"><div class="company-name">Eli Lilly</div><div class="company-code"><span class="rank d-none"></span>LLY</div></a></div></td>, <td class="td-right" data-sort="915194249216"><span class="currency-symbol-left">$</span>915.19 B</td>, <td class="td-right" data-sort="102630">$1,026</td>, <td class="rh-sm" data-sort="48"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.48%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,24 L5,19 L10,19 L15,22 L20,24 L25,26 L30,29 L35,30 L40,25 L45,26 L50,30 L55,26 L60,27 L65,34 L70,37 L75,36 L80,41 L85,23 L90,17 L95,16 L100,11 L105,12 L110,14 L115,20 L120,16 L125,11 L130,6 L135,7 L140,8 L145,11 L150,4 L155,3"></path></svg></td>, <td>🇺🇸 <span class="responsive-hidden">USA</span></td>]
['', '14', 'Eli LillyLLY', '$915.19 B', '$1,026', '0.48%', '', '🇺🇸 USA']
[<td class="fav"><img alt="favorite icon" data-id="69141" data-type="company" src="/img/fav.svg?v2"/></td>, <td class="rank-td td-right" data-sort="15">15</td>, <td class="name-td"><div class="logo-container"><img alt="SK Hynix logo" class="company-logo" loading="lazy" src="/img/company-logos/64/000660.KS.png"/></div><div class="name-div"><a href="/sk-hynix/marketcap/"><div class="company-name">SK Hynix</div><div class="company-code"><span class="rank d-none"></span>000660.KS</div></a></div></td>, <td class="td-right" data-sort="822491493536"><span class="currency-symbol-left">$</span>822.49 B</td>, <td class="td-right" data-sort="115868">$1,159</td>, <td class="rh-sm" data-sort="0"><span class="percentage-green"><svg class="a" viewbox="0 0 12 12"><path d="M10 8H2l4-4 4 4z"></path></svg>0.00%</span></td>, <td class="p-0 sparkline-td green"><svg><path d="M0,41 L5,37 L10,38 L15,37 L20,37 L25,34 L30,33 L35,32 L40,33 L45,32 L50,30 L55,30 L60,30 L65,30 L70,28 L75,27 L80,27 L85,28 L90,28 L95,22 L100,22 L105,16 L110,15 L115,13 L120,6 L125,8 L130,3 L135,3 L140,9 L145,8 L150,11 L155,11"></path></svg></td>, <td>🇰🇷 <span class="responsive-hidden">S. Korea</span></td>]
['', '15', 'SK Hynix000660.KS', '$822.49 B', '$1,159', '0.00%', '', '🇰🇷 S. Korea']

In [20]:
df.columns

Index(['', 'Rank', 'Name', 'Market Cap', 'Price', 'Today', 'Price (30 days)',
       'Country'],
      dtype='object')

In [21]:
for row in column_data:
    row_data = row.find_all('td')
    individual_data = [data.text.strip() for data in row_data]

    if len(individual_data) == len(df.columns):
        df.loc[len(df)] = individual_data

In [22]:
df.head()

,,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,,1,NVIDIANVDA,$5.443 T,$224.76,1.88%,,🇺🇸 USA
1,,2,Alphabet (Google)GOOG,$4.632 T,$382.40,0.65%,,🇺🇸 USA
2,,3,AppleAAPL,$4.407 T,$300.12,0.38%,,🇺🇸 USA
3,,4,MicrosoftMSFT,$3.077 T,$414.24,0.76%,,🇺🇸 USA
4,,5,AmazonAMZN,$2.825 T,$262.65,1.28%,,🇺🇸 USA

In [23]:
df.tail()

,,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
95,,96,ABBABBN.SW,$187.22 B,$103.13,2.33%,,🇨🇭 Switzerland
96,,97,Toronto Dominion BankTD,$182.69 B,$108.96,0.97%,,🇨🇦 Canada
97,,98,InditexITX.MC,$181.05 B,$58.13,0.64%,,🇪🇸 Spain
98,,99,SoftBank Group Corp.9984.T,$180.45 B,$31.67,6.01%,,🇯🇵 Japan
99,,100,Arista NetworksANET,$179.17 B,$142.30,0.51%,,🇺🇸 USA

In [24]:
df.drop(columns=['Price (30 days)'], inplace = True)
df.head()

    Rank                   Name Market Cap    Price  Today Country
0      1             NVIDIANVDA   $5.443 T  $224.76  1.88%  🇺🇸 USA
1      2  Alphabet (Google)GOOG   $4.632 T  $382.40  0.65%  🇺🇸 USA
2      3              AppleAAPL   $4.407 T  $300.12  0.38%  🇺🇸 USA
3      4          MicrosoftMSFT   $3.077 T  $414.24  0.76%  🇺🇸 USA
4      5             AmazonAMZN   $2.825 T  $262.65  1.28%  🇺🇸 USA

In [25]:
df.tail()

,,Rank,Name,Market Cap,Price,Today,Country
95,,96,ABBABBN.SW,$187.22 B,$103.13,2.33%,🇨🇭 Switzerland
96,,97,Toronto Dominion BankTD,$182.69 B,$108.96,0.97%,🇨🇦 Canada
97,,98,InditexITX.MC,$181.05 B,$58.13,0.64%,🇪🇸 Spain
98,,99,SoftBank Group Corp.9984.T,$180.45 B,$31.67,6.01%,🇯🇵 Japan
99,,100,Arista NetworksANET,$179.17 B,$142.30,0.51%,🇺🇸 USA

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0               100 non-null    object
 1   Rank        100 non-null    object
 2   Name        100 non-null    object
 3   Market Cap  100 non-null    object
 4   Price       100 non-null    object
 5   Today       100 non-null    object
 6   Country     100 non-null    object
dtypes: object(7)
memory usage: 6.2+ KB

In [27]:
df.drop(df.columns[0], axis = 1, inplace = True)
df

   Rank                        Name Market Cap    Price  Today         Country
0     1                  NVIDIANVDA   $5.443 T  $224.76  1.88%          🇺🇸 USA
1     2       Alphabet (Google)GOOG   $4.632 T  $382.40  0.65%          🇺🇸 USA
2     3                   AppleAAPL   $4.407 T  $300.12  0.38%          🇺🇸 USA
3     4               MicrosoftMSFT   $3.077 T  $414.24  0.76%          🇺🇸 USA
4     5                  AmazonAMZN   $2.825 T  $262.65  1.28%          🇺🇸 USA
..  ...                         ...        ...      ...    ...             ...
95   96                  ABBABBN.SW  $187.22 B  $103.13  2.33%  🇨🇭 Switzerland
96   97     Toronto Dominion BankTD  $182.69 B  $108.96  0.97%       🇨🇦 Canada
97   98               InditexITX.MC  $181.05 B   $58.13  0.64%        🇪🇸 Spain
98   99  SoftBank Group Corp.9984.T  $180.45 B   $31.67  6.01%        🇯🇵 Japan
99  100         Arista NetworksANET  $179.17 B  $142.30  0.51%          🇺🇸 USA

[100 rows x 6 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rank        100 non-null    object
 1   Name        100 non-null    object
 2   Market Cap  100 non-null    object
 3   Price       100 non-null    object
 4   Today       100 non-null    object
 5   Country     100 non-null    object
dtypes: object(6)
memory usage: 5.5+ KB

In [29]:
df.to_excel('companies_market_cap.xlsx', index = False)